import test from 'node:test';
import assert from 'node:assert/strict';
import {themes,filterThemes} from '../dist/catalog.js';
import {renderBlogger,renderPreview,packageFiles,config} from '../dist/engine.js';
import {zipBytes,crc32} from '../dist/zip.js';
test('search combines category, favorites, accents, and sort',()=>{assert.equal(filterThemes().length,12);assert.equal(filterThemes({category:'rental'}).length,2);assert.equal(filterThemes({query:'wnetrza'})[0].id,'studio');assert.equal(filterThemes({category:'shop',favorites:['studio','object']})[0].id,'object');assert.equal(filterThemes({query:'no-matching-theme'}).length,0);assert.equal(filterThemes({sort:'az'})[0].id,'atelier');});
test('all localized exports contain dynamic Blogger data and separate pages',()=>{for(const theme of themes)for(const lang of ['pl','en']){const xml=renderBlogger(theme,lang);assert.match(xml,/<data:post.body\/>/);assert.match(xml,/<b:skin><!\[CDATA\[/);assert.match(xml,/error_page/);assert.match(xml,/data:olderPageUrl/);assert.match(xml,/data:post.comments/);const files=packageFiles(theme,lang);assert.equal(Object.keys(files).length,12);assert.match(files['pages/about.html'],/<h1>/);assert.doesNotMatch(files['content/article.html'],/<h1>/);assert.doesNotMatch(files['preview/home.html'],/<script>/);assert.match(files['preview/home.html'],/href="about.html"/);assert.match(files['INSTALL.txt'],/about.html/);for(const page of theme.pages)assert.match(renderPreview(theme,page,lang),/<main>[\s\S]+<\/main>/);}});
test('user values cannot escape HTML or CSS and flow into both exports',()=>{const theme=themes[0],opts={brand:'A & B <script>alert(1)</script>',accent:'#123abc',font:'sans',email:'team@example.org'};const xml=renderBlogger(theme,'en',opts);assert.match(xml,/A &amp; B &lt;script&gt;/);assert.doesNotMatch(xml,/<script>alert/);assert.match(xml,/--accent:#123abc/);assert.match(packageFiles(theme,'en',opts)['pages/contact.html'],/mailto:team@example.org/);assert.equal(config(theme,{accent:'red;}body{display:none',font:'bad',email:'bad'}).accent,theme.accent);});
test('ZIP entries round-trip including Unicode and CRC integrity',()=>{const files={'pages/żółć.html':'Zażółć gęślą jaźń','theme.xml':renderBlogger(themes[2])};const bytes=zipBytes(files),view=new DataView(bytes.buffer);let offset=0;for(const [name,data] of Object.entries(files)){assert.equal(view.getUint32(offset,true),0x04034b50);const size=view.getUint32(offset+18,true),length=view.getUint16(offset+26,true);assert.equal(new TextDecoder().decode(bytes.slice(offset+30,offset+30+length)),name);const body=bytes.slice(offset+30+length,offset+30+length+size);assert.equal(new TextDecoder().decode(body),data);assert.equal(view.getUint32(offset+14,true),crc32(body));offset+=30+length+size;}assert.equal(view.getUint32(offset,true),0x02014b50);assert.equal(view.getUint32(bytes.length-22,true),0x06054b50);assert.equal(crc32(new TextEncoder().encode('123456789')),0xcbf43926);});
